# Generated by Django 5.0 on 2024-01-05 05:12

import tour.oauth2.generators
import tour.oauth2.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'accessToken',
                'verbose_name_plural': 'accessTokens',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id',
                 models.CharField(db_index=True, default=tour.oauth2.generators.generate_client_id, max_length=100,
                                  unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated',
                                                   validators=[tour.oauth2.validators.validate_uris])),
                ('client_type',
                 models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(
                    choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'),
                             ('password', 'Resource owner password-based'),
                             ('client-credentials', 'Client credentials')], max_length=32)),
                ('client_secret',
                 models.CharField(blank=True, db_index=True, default=tour.oauth2.generators.generate_client_secret,
                                  max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grant',
                'verbose_name_plural': 'grants',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'refreshToken',
                'verbose_name_plural': 'refreshTokens',
            },
        ),
    ]
