# Generated by Django 4.2.9 on 2024-03-14 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_alter_accesstoken_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 6, 30, 1, 322737, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
