# Generated by Django 4.2.9 on 2024-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='language',
            field=models.ManyToManyField(related_name='packages', to='agency.language'),
        ),
    ]
