# Generated by Django 4.2.9 on 2024-02-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'hotel', 'verbose_name_plural': 'hotel_list'},
        ),
        migrations.RenameField(
            model_name='tourpackage',
            old_name='hotel',
            new_name='hotels',
        ),
    ]
