# Generated by Django 4.2.9 on 2024-01-25 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_tourpackage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
