# Generated by Django 4.2.9 on 2024-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='licence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempcompany',
            name='licence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
