# Generated by Django 4.2.9 on 2024-02-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_activity_booking_category_city_country_destination_and_more'),
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='activities',
            field=models.ManyToManyField(blank=True, to='agency.activity'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.ManyToManyField(blank=True, to='agency.category'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='agency.destination'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='agency.hotel'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='options',
            field=models.ManyToManyField(blank=True, to='agency.options'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_from', to='agency.city'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_to', to='agency.city'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('profile', 'package'), name='Per User Per Package'),
        ),
    ]
