# Generated by Django 4.2.9 on 2024-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_company_licence_tempcompany_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
