# Generated by Django 4.2.9 on 2024-01-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_company_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
