# Generated by Django 4.2.9 on 2024-01-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_company_average_rating_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_from', to='agency.city'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_to', to='agency.city'),
        ),
    ]
