# Generated by Django 4.2.9 on 2024-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_city_lat_city_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
