# Generated by Django 4.2.9 on 2024-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_tourpackage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='options_included',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.ManyToManyField(blank=True, to='agency.category'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='options_included',
            field=models.ManyToManyField(blank=True, to='agency.options'),
        ),
    ]
