# Generated by Django 4.2.9 on 2024-01-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_city_alter_tourpackage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
