# Generated by Django 4.2.9 on 2024-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_tourpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
