# Generated by Django 4.2.9 on 2024-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_company_is_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
