# Generated by Django 4.2.9 on 2024-02-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_remove_tourpackage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='location',
        ),
    ]
