# Generated by Django 4.2.9 on 2024-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_tourpackage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='https://tour-guide-bucket.s3.eu-north-1.amazonaws.com/images/default-agency-image.png'),
        ),
    ]
