# Generated by Django 4.2.9 on 2024-03-17 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_company_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='verified_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
    ]
