# Generated by Django 4.2.9 on 2024-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='activities',
            field=models.ManyToManyField(blank=True, to='agency.activity'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='agency.destination'),
        ),
    ]
