# Generated by Django 4.2.9 on 2024-01-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_destination_theme_city_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='destination',
            new_name='destinations',
        ),
    ]
