# Generated by Django 4.2.9 on 2024-03-17 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_company_updated_time_company_verified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), blank=True, editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='verified_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='updated_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), blank=True, editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='verified_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, editable=False, null=True, size=None),
        ),
    ]
