# Generated by Django 4.2.9 on 2024-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_rename_destination_city_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['starting_date']},
        ),
    ]
