# Generated by Django 4.2.9 on 2024-02-24 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0009_alter_tourpackage_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
