# Generated by Django 4.2.9 on 2024-04-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_company_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
