# Generated by Django 4.2.9 on 2024-02-24 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0010_alter_company_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='agency.hotel'),
        ),
    ]
