# Generated by Django 4.2.9 on 2024-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_alter_hotel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
