# Generated by Django 4.2.9 on 2024-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_activity_delete_theme_alter_tourpackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='activities',
            field=models.ManyToManyField(to='agency.activity'),
        ),
    ]
