# Generated by Django 4.2.9 on 2024-02-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_alter_company_admin_remove_tourpackage_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='hotel',
            new_name='hotels',
        ),
    ]
