# Generated by Django 4.2.9 on 2024-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_remove_city_activities_remove_city_destinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='features',
            field=models.ManyToManyField(limit_choices_to=5, to='agency.features'),
        ),
    ]
