# Generated by Django 4.2.9 on 2024-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_rename_hotel_tourpackage_hotels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='options_included',
            new_name='options',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='default-agency-image.png'),
        ),
    ]
