# Generated by Django 4.2.9 on 2024-02-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_alter_city_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
