# Generated by Django 4.2.9 on 2024-02-05 04:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_rename_features_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=10),
        ),
    ]
