# Generated by Django 4.2.9 on 2024-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_tourpackage_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-starting_date']},
        ),
        migrations.AddField(
            model_name='company',
            name='tg_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
