# Generated by Django 4.2.9 on 2024-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_alter_tourpackage_options_company_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
