# Generated by Django 4.2.9 on 2024-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_tourpackage_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chat_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
