# Generated by Django 4.2.9 on 2024-02-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_hotel_tourpackage_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
