# Generated by Django 4.2.9 on 2024-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
