# Generated by Django 4.2.9 on 2024-02-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_alter_feature_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
