# Generated by Django 4.2.9 on 2024-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_rename_phone_number_company_phone_number_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='Tashkent', max_length=95),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='licence_number',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
