# Generated by Django 4.2.9 on 2024-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0027_alter_company_address_alter_company_licence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number_2', models.CharField(blank=True, max_length=30, null=True)),
                ('licence_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=95)),
                ('tg_username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
