# Generated by Django 4.2.9 on 2024-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_tempcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='licence_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tempcompany',
            name='licence_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tempcompany',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
