# Generated by Django 4.2.9 on 2024-02-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_alter_company_licence_number_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_bot_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tempcompany',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempcompany',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
