# Generated by Django 4.2.9 on 2024-02-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_company_is_bot_connected_company_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tempcompany',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
