# Generated by Django 4.2.9 on 2024-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_alter_company_name_alter_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcompany',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
