# Generated by Django 5.0 on 2024-01-05 05:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_code', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'user tem',
                'verbose_name_plural': 'Temp model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('expires', models.DateTimeField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('temp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='user_sms', to='user.temp')),
            ],
            options={
                'verbose_name': 'User sms',
                'index_together': {('phone_number', 'code')},
            },
        ),
    ]
