# Generated by Django 4.2.9 on 2024-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_booking_options_booking_created_at_and_more'),
        ('user', '0004_alter_profile_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packages',
            field=models.ManyToManyField(blank=True, null=True, to='agency.tourpackage'),
        ),
    ]
