# Generated by Django 4.2.9 on 2024-02-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_delete_reviews'),
        ('user', '0004_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='packages',
            field=models.ManyToManyField(to='agency.tourpackage'),
        ),
    ]
