# Generated by Django 4.2.9 on 2024-02-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_tourpackage_language'),
        ('user', '0005_alter_profile_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packages',
            field=models.ManyToManyField(blank=True, to='agency.tourpackage'),
        ),
    ]
