# Generated by Django 4.2.9 on 2024-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default='https://tour-guide-bucket.s3.eu-north-1.amazonaws.com/images/default-user-image.png'),
        ),
    ]
